name: quora_challenge_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - numpy>=1.23
  - scipy>=1.9
  - pandas>=1.5
  - scikit-learn>=1.1
  - joblib>=1.2
  - reportlab>=4.0
  - jupyter
  - notebook
  - ipykernel
  - pip
